name: run-integration-test

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run MySQL  
        run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'

      - name: Set Up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Check Go Installation
        run: go version

      - name:   Download go dependencies
        run: go mod download

      - name: Run Go Integration Test
        run: |
          pwd
          export DB_HOST=127.0.0.1
          export DB_PORT=8888
          export DB_USER=root
          export DB_PASSWORD=password
          export DB_NAME=test
          echo $DB_HOST
          go test
